{
  parserClass="se.ch.HAnS.featureModel.parser.FeatureModelParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="FeatureModel"
  psiImplClassSuffix="Impl"
  psiPackage="se.ch.HAnS.featureModel.psi"
  psiImplPackage="se.ch.HAnS.featureModel.psi.impl"

  elementTypeHolderClass="se.ch.HAnS.featureModel.psi.FeatureModelTypes"
  elementTypeClass="se.ch.HAnS.featureModel.psi.FeatureModelElementType"
  tokenTypeClass="se.ch.HAnS.featureModel.psi.FeatureModelTokenType"
}

featureModelFile ::= projectName ((CRLF)* feature)* (('\t'|CRLF)*)

projectName ::= FEATURENAME

feature ::= (FEATURENAME | '\t' feature)