{
  parserClass="se.ch.HAnS.featureToFolder.parser.FeatureToFolderParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="FeatureToFolder"
  psiImplClassSuffix="Impl"
  psiPackage="se.ch.HAnS.featureToFolder.psi"
  psiImplPackage="se.ch.HAnS.featureToFolder.psi.impl"

  elementTypeHolderClass="se.ch.HAnS.featureToFolder.psi.FeatureToFolderTypes"
  elementTypeClass="se.ch.HAnS.featureToFolder.psi.FeatureToFolderElementType"
  tokenTypeClass="se.ch.HAnS.featureToFolder.psi.FeatureToFolderTokenType"
}

featureToFolderFile ::= CRLF* lpq (CRLF* ','* CRLF* lpq)* CRLF*

lpq ::= FEATURENAME ('::'FEATURENAME)*