{
  parserClass="se.ch.HAnS.folderAnnotation.parser.FolderAnnotationParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="FolderAnnotation"
  psiImplClassSuffix="Impl"
  psiPackage="se.ch.HAnS.folderAnnotation.psi"
  psiImplPackage="se.ch.HAnS.folderAnnotation.psi.impl"

  elementTypeHolderClass="se.ch.HAnS.folderAnnotation.psi.FolderAnnotationTypes"
  elementTypeClass="se.ch.HAnS.folderAnnotation.psi.FolderAnnotationElementType"
  tokenTypeClass="se.ch.HAnS.folderAnnotation.psi.FolderAnnotationTokenType"

  psiImplUtilClass="se.ch.HAnS.folderAnnotation.psi.impl.FolderAnnotationPsiImplUtil"
}

featureToFolderFile ::= CRLF* lpq (CRLF* CS* CRLF* lpq)* CRLF*

lpq ::= FEATURENAME (SEPARATOR FEATURENAME)* {
mixin="se.ch.HAnS.folderAnnotation.psi.impl.FolderAnnotationNamedElementImpl"
implements="se.ch.HAnS.folderAnnotation.psi.FolderAnnotationNamedElement"
methods=[getName setName getNameIdentifier]}