{
  parserClass="se.ch.HAnS.folderAnnotations.parser.FolderAnnotationParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="FolderAnnotation"
  psiImplClassSuffix="Impl"
  psiPackage="se.ch.HAnS.folderAnnotations.psi"
  psiImplPackage="se.ch.HAnS.folderAnnotations.psi.impl"

  elementTypeHolderClass="se.ch.HAnS.folderAnnotations.psi.FolderAnnotationTypes"
  elementTypeClass="se.ch.HAnS.folderAnnotations.psi.FolderAnnotationElementType"
  tokenTypeClass="se.ch.HAnS.folderAnnotations.psi.FolderAnnotationTokenType"
}

featureToFolderFile ::= CRLF* lpq (CRLF* CS* CRLF* lpq)* CRLF*

lpq ::= FEATURENAME (SEPARATOR FEATURENAME)*