{
  parserClass="se.ch.HAnS.codeAnnotations.parser.CodeAnnotationParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="CodeAnnotation"
  psiImplClassSuffix="Impl"
  psiPackage="se.ch.HAnS.codeAnnotations.psi"
  psiImplPackage="se.ch.HAnS.codeAnnotations.psi.impl"

  elementTypeHolderClass="se.ch.HAnS.codeAnnotations.psi.CodeAnnotationTypes"
  elementTypeClass="se.ch.HAnS.codeAnnotations.psi.CodeAnnotationElementType"
  tokenTypeClass="se.ch.HAnS.codeAnnotations.psi.CodeAnnotationTokenType"
}

marker ::= (beginmarker|endmarker|linemarker)

beginmarker ::= BEGIN SPACE* parameter
endmarker ::= END SPACE* parameter
linemarker ::= LINE SPACE* parameter

parameter ::= (OBRACKET SPACE* lpq ((SPACE* CS)? SPACE+ lpq)* SPACE* CBRACKET)

lpq ::= FEATURENAME (SEPARATOR FEATURENAME)*