name: Auto Assign

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: 'Auto-assign PR'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          teams: hans-reviewers
          numOfAssignee: 1
          teamIsPullRequestReviewer: true
