name: AutoMerge Changelog

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  automerge:
    name: Auto-Approve & Merge Changelog PR
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
      GH_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Authenticate GitHub CLI with Bot Token
        run: echo "${{ secrets.BOT_TOKEN }}" | gh auth login --with-token

      - name: Find Changelog PR
        id: find_pr
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          PR_URL=$(gh pr list --search "Changelog update - \`$VERSION\`" --json url -q '.[0].url')
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT

      - name: Get Changed Files
        id: changed_files
        run: |
          FILES=$(gh pr view "${{ steps.find_pr.outputs.pr_url }}" --json files -q '.files[].path')
          echo "files=$FILES" >> $GITHUB_OUTPUT

      - name: Check if only CHANGELOG.md was changed
        id: check_changelog_only
        run: |
          FILES="${{ steps.changed_files.outputs.files }}"
          if [[ "$FILES" == "CHANGELOG.md" ]]; then
            echo "only_changelog=true" >> $GITHUB_OUTPUT
          else
            echo "only_changelog=false" >> $GITHUB_OUTPUT
          fi

      - name: Approve PR via REST API
        if: steps.check_changelog_only.outputs.only_changelog == 'true'
        run: gh pr review "${{ steps.find_pr.outputs.pr_url }}" -a -b "Auto-approved by bot."

      - name: Squash Merge PR
        if: steps.check_changelog_only.outputs.only_changelog == 'true'
        run: gh pr merge "${{ steps.find_pr.outputs.pr_url }}" -s -d --auto